spring.application.name=ProyectoVuelosOsorio
#spring.security.user.name=
#spring.security.user.password=


# Configuración de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/proyecto_vuelos?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

## Configuración para Thymeleaf
#spring.thymeleaf.enabled=true
#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html
#spring.thymeleaf.mode=HTML5


logging.level.org.springframework.security=DEBUG